// Mocks generated by Mockito 5.4.6 from annotations
// in test_quest/test/auth/view/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i6;
import 'package:test_quest/auth/model/signup_form.dart' as _i8;
import 'package:test_quest/repository/firebase/auth/firebase_auth_repository_impl.dart'
    as _i7;
import 'package:test_quest/repository/firebase/user/user_firestore_repository.dart'
    as _i9;
import 'package:test_quest/user/model/user_info.dart' as _i3;
import 'package:test_quest/util/service/permission_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserInfo_1 extends _i1.SmartFake implements _i3.UserInfo {
  _FakeUserInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i4.PermissionService {
  @override
  _i5.Future<_i6.PermissionStatus> requestNotificationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestNotificationPermission, []),
            returnValue: _i5.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
            returnValueForMissingStub: _i5.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
          )
          as _i5.Future<_i6.PermissionStatus>);

  @override
  _i5.Future<_i6.PermissionStatus> requestCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestCameraPermission, []),
            returnValue: _i5.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
            returnValueForMissingStub: _i5.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
          )
          as _i5.Future<_i6.PermissionStatus>);

  @override
  _i5.Future<_i6.PermissionStatus> requestPhotoPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPhotoPermission, []),
            returnValue: _i5.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
            returnValueForMissingStub: _i5.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
          )
          as _i5.Future<_i6.PermissionStatus>);

  @override
  _i5.Future<_i6.PermissionStatus> requestTrackingPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestTrackingPermission, []),
            returnValue: _i5.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
            returnValueForMissingStub: _i5.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
          )
          as _i5.Future<_i6.PermissionStatus>);
}

/// A class which mocks [FirebaseAuthRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthRepositoryImpl extends _i1.Mock
    implements _i7.FirebaseAuthRepositoryImpl {
  @override
  _i5.Future<_i2.UserCredential> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> signup({required _i8.SignupForm? data}) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {#data: data}),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signup, [], {#data: data}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signup, [], {#data: data}),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i2.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i5.Stream<_i2.User?>.empty(),
            returnValueForMissingStub: _i5.Stream<_i2.User?>.empty(),
          )
          as _i5.Stream<_i2.User?>);

  @override
  _i5.Future<_i2.UserCredential> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);
}

/// A class which mocks [UserFirestoreRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserFirestoreRepositoryImpl extends _i1.Mock
    implements _i9.UserFirestoreRepositoryImpl {
  @override
  _i5.Future<void> setUser(_i3.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#setUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [uid]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateUser(_i3.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserInfo?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i5.Future<_i3.UserInfo?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.UserInfo?>.value(),
          )
          as _i5.Future<_i3.UserInfo?>);

  @override
  _i5.Future<_i3.UserInfo> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i3.UserInfo>.value(
              _FakeUserInfo_1(this, Invocation.method(#getCurrentUser, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.UserInfo>.value(
              _FakeUserInfo_1(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i5.Future<_i3.UserInfo>);
}
